### PR TITLE
Change default redis key expiration to 1 minute

### PR DESCRIPTION
**Pull request by alexlance**
If for some reason a process invoked with cronlock does not complete - then a stale cronlock key
can remain in the redis cache. If the cronjob is set to run every say 10 minutes, then it will not be
able to run for the next 24 hours (86400 seconds according to the value in CRONLOCK_RELEASE).

This means the cronjob that should be firing every ten minutes doesn't run for a whole day. This is
a bit unexpected. A more predictable behaviour would be for the system to gracefully continue running
the cron job.

Since the minimum granularity of cron is 1 minute, a cache timeout of 60 seconds should be fine. (It could probably be considered a malfunctioning environment if the clock skew amongst your cron cluster exceeded a minute - and thus not the responsibility of cronlock to continue to function successfully).

If you're curious as to why the cronlock process wasn't completing, the instance hosting cron was unexpectedly shutdown, which meant the cronlock couldn't complete and remove its redis key.

### CODE REVIEW

**Comment by maxnasonov** [comment]
So by default any command should take less than one minute without making cronlock useless? It would be even more unexpected. The current default value makes more sense and you should just change its variable according to your needs.

**Comment by alexlance** [comment]
That's not what I'm saying. It is very unexpected behaviour for a job that is meant to run every ten minutes, to fail once (and subsequently not release its lock), and then not run again for 24 hours.

**Comment by kvz** [comment]
Thanks for contributing but I'm not +1 on this change. If cronlock doesn't release (a lot) we should figure out why. The release feature is for edge cases to make sure you don't have stales forever. With this change, cronlock would be rendered useless for any script that runs longer than 60 seconds. Which may not be a valid thing in your case, but surely there are scripts out there (speaking from personal experience i can already name a few) that need to run longer.

Sorry!

**Comment by alexlance** [comment]
All good, it's fine to close the PR - but thought I'd just take some time to explain my                                                          
reasoning a bit more.                                                                                                                   
                                                                                                                                        
We use cronlock on a cluster of cron servers (with identical cron schedules) to ensure
that even if one server fails, that another server will pick up the scheduled jobs instead.

Now in this cluster of servers it is common to detect that one of the servers
has gotten unhealthy or needs to be rebuilt for one reason or another. Thus it
is common to shutdown and terminate one of the cron servers (ie immutable
infrastructure). It isn't just a possibility that a server will be terminated
*during* a job, it is likely.

And if a server is terminated during a job, then the redis key will not be
released. And a job that is scheduled to run, eg once every minute, won't run
again until - by default - a day later.

The only use case I can see where having a release time of 60 seconds would be
problematic would be in the case where you want a job to run every 60 seconds -
and if that job takes longer than 60 seconds, you would like to *prevent further
invocations* of the job on the very next minute.

This isn't the way we use cronlock, but I could see how it might be useful.

My opinion is that if the cron recipe says once per minute, then absolutely, once per 
minute the job should be fired off, regardless of whether a previous invocation
is still running.

Anyway cheers for the feedback - and the very useful tool - as you've mentioned the
env var can be overriden so we'll continue doing that.

**Comment by kvz** [comment]
I think you should be able to get a signal when the server is about to shutdown and clear the lock, just a though!

**Pull request closed without merging**
